development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ssnzavtzmyowvk:82ede51fa5bc5fcaa04a41d4c8b6e3c3d260c71222e4bdd721ba7b60c4df1a0d@ec2-54-243-223-245.compute-1.amazonaws.com:5432/devtm15lrpklbf
  channel_prefix: my_test_app_production
